# Generated by Django 3.0.5 on 2020-04-27 13:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Name')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Name')),
                ('gender', models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, verbose_name='Gender')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('contact', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('class_study', models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Class Study')),
                ('school', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landmark')),
                ('addess', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('ditrict', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('pin', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Pin')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Home Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tid', models.CharField(max_length=12, unique=True)),
                ('success', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trn_type', models.CharField(max_length=20)),
                ('remarks', models.CharField(default='NA', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RangotsavUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Name')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Name')),
                ('gender', models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, verbose_name='Gender')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('contact', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('landmark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landmark')),
                ('addess', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('ditrict', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('pin', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Pin')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Home Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RANGOTSAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInput', models.CharField(default='11', max_length=2)),
                ('category', models.CharField(choices=[('', 'select'), ('Junior', 'Below 13 years'), ('Senior', 'Above or equal to 13 yrs')], max_length=12, verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user2WithDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to='navprayas.PrUser')),
                ('user3WithDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navprayas.PrUser')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mother Name')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Father Name')),
                ('gender', models.CharField(blank=True, choices=[('', 'select'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50, verbose_name='Gender')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('contact', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Contact')),
                ('class_study', models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Class Study')),
                ('school', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landmark')),
                ('addess', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('ditrict', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('pin', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Pin')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Home Number')),
                ('completeProfile', models.BooleanField(default=False)),
                ('allowEdit', models.CharField(default='000', max_length=3)),
                ('blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInput', models.CharField(default='11', max_length=2)),
                ('category', models.CharField(choices=[('', 'select'), ('G1', 'Upto 13 yrs'), ('G2', 'From 14 to 17 yrs'), ('G3', 'Above 17 yrs')], max_length=12, verbose_name='Category')),
                ('success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user2WithDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to='navprayas.PrUser')),
                ('user3WithDetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navprayas.PrUser')),
            ],
        ),
        migrations.CreateModel(
            name='MTSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpl', models.CharField(choices=[], max_length=9, verbose_name='Paper langauge')),
                ('success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('', 'select'), ('Junior', 'V/VI/VII'), ('Senior', 'VIII/IX/X')], max_length=12, verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='media/navprayas/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CHESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[], max_length=12, verbose_name='Category')),
                ('success', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'select'), ('G1', 'Upto 13 yrs'), ('G2', 'From 14 to 17 yrs'), ('G3', 'Above 17 yrs')], max_length=12, verbose_name='Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
