# Generated by Django 3.0.5 on 2020-04-27 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navprayas', '0002_auto_20200427_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fhs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mtse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pr',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='user2WithDetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='+', to='navprayas.RangotsavUser'),
        ),
        migrations.AlterField(
            model_name='rangotsav',
            name='user3WithDetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navprayas.RangotsavUser'),
        ),
    ]
